// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDJEZNOoabeihEBrZolH0DfoxjQTt-TeA',
    appId: '1:515434819795:web:106ca99efbc8cc00ab2426',
    messagingSenderId: '515434819795',
    projectId: 'fir-flutter-codelab-92b18',
    authDomain: 'fir-flutter-codelab-92b18.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-92b18.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYH_xrb7bu4ds9gCHJ8szWNF1_4OTYEFY',
    appId: '1:515434819795:android:50395b2eea9f83baab2426',
    messagingSenderId: '515434819795',
    projectId: 'fir-flutter-codelab-92b18',
    storageBucket: 'fir-flutter-codelab-92b18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIDtSRvwpsB2C_J1v54MllP3yuM0pILSg',
    appId: '1:515434819795:ios:d405a1e82b0d8b05ab2426',
    messagingSenderId: '515434819795',
    projectId: 'fir-flutter-codelab-92b18',
    storageBucket: 'fir-flutter-codelab-92b18.appspot.com',
    iosBundleId: 'com.example.teamCheckMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIDtSRvwpsB2C_J1v54MllP3yuM0pILSg',
    appId: '1:515434819795:ios:d405a1e82b0d8b05ab2426',
    messagingSenderId: '515434819795',
    projectId: 'fir-flutter-codelab-92b18',
    storageBucket: 'fir-flutter-codelab-92b18.appspot.com',
    iosBundleId: 'com.example.teamCheckMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDJEZNOoabeihEBrZolH0DfoxjQTt-TeA',
    appId: '1:515434819795:web:4a1aef7f566e6839ab2426',
    messagingSenderId: '515434819795',
    projectId: 'fir-flutter-codelab-92b18',
    authDomain: 'fir-flutter-codelab-92b18.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-92b18.appspot.com',
  );
}
